# Generated by Django 3.0.5 on 2020-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('user_handle', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('user_imageURL', models.CharField(default='src/assets/images/profile.jpg', max_length=250)),
                ('tweet_id', models.CharField(blank=True, max_length=250, null=True)),
                ('tweet_text', models.TextField()),
                ('tweet_mediaURL', models.URLField(blank=True, max_length=250)),
                ('tweet_URL', models.URLField(default='https://twitter.com', max_length=250)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
