# Generated by Django 3.0.5 on 2020-04-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_name',
            new_name='username',
        ),
    ]
